// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolTime.Data;

#nullable disable

namespace ToolTime.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706011705_mRequest")]
    partial class mRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToolTime.Models.CheckoutRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualReturn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedReturnDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckoutRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckoutDateTime = new DateTime(2025, 7, 4, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1189),
                            ExpectedReturnDateTime = new DateTime(2025, 7, 11, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1190),
                            ToolId = 1,
                            UserId = "johndoe123"
                        });
                });

            modelBuilder.Entity("ToolTime.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 3, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1209),
                            IssueDesc = "Battery not charging properly",
                            Status = "Open",
                            ToolId = 1,
                            UserId = "johndoe123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 26, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1211),
                            IssueDesc = "Blade guard is loose",
                            ResolvedAt = new DateTime(2025, 7, 1, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1212),
                            Status = "Resolved",
                            ToolId = 2,
                            UserId = "johndoe123"
                        });
                });

            modelBuilder.Entity("ToolTime.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastInspectionDate = new DateTime(2025, 6, 26, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1159),
                            Name = "Makita Hammer Drill",
                            SerialNumber = "SN12345",
                            Type = "Drill"
                        },
                        new
                        {
                            Id = 2,
                            LastInspectionDate = new DateTime(2025, 7, 1, 1, 17, 4, 744, DateTimeKind.Utc).AddTicks(1170),
                            Name = "Bosch Circular Saw",
                            SerialNumber = "SN98765",
                            Type = "Saw"
                        });
                });

            modelBuilder.Entity("ToolTime.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "johndoe123",
                            FirstName = "John",
                            LastName = "Doe",
                            Role = "User"
                        },
                        new
                        {
                            Id = "admin001",
                            FirstName = "Bill",
                            LastName = "Wriley",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ToolTime.Models.CheckoutRecord", b =>
                {
                    b.HasOne("ToolTime.Models.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolTime.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToolTime.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("ToolTime.Models.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolTime.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
